server:
  port: 8090
  max-http-header-size: 512KB

eureka:
  client:
    eureka-service-url-poll-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultServer: http://${SERVICE_REGISTRY_HOSTNAME}:8761/eureka/
  instance:
    non-secure-port: 8080
    appname: api-gateway
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

spring:
  profiles:
    default: production
  application:
    name: api-gateway
    gateway:
      httpclient:
        response-timeout: 1h
      discovery:
        locator:
          enabled: false
