server:
  port: 8090
  max-http-header-size: 512KB

eureka:
  client:
    eureka-service-url-poll-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOSTNAME}:8761/eureka/
    registry-fetch-interval-seconds: 5
    webclient:
      enabled: true
  instance:
    non-secure-port: 8090
    appname: api-gateway
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 1
spring:
  profiles:
    default: production
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      httpclient:
        response-timeout: 1h
      discovery:
        locator:
          enabled: false
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**
        - id: google
          uri: http://google.com
          predicates:
            - Path=/google/**
          metadata:
            scope: "admin"
      default-filters:
        - RewritePath=(?<serviceId>/[^/]+)/(?<path>/?.*), /$\{path}
        - TokenRelay=

logging:
  level:
    com.netflix.discovery: warn
