server:
  port: 8090
  max-http-header-size: 512KB

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        response-timeout: 1h
      routes:
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/auth/**
        - id: google
          uri: https://google.com/
          predicates:
            - Path=/google/**
          metadata:
            scope: "admin"
      default-filters:
        - RewritePath=(?<serviceId>/[^/]+)/(?<path>/?.*), /$\{path}
        - TokenRelay=

logging:
  level:
    com.netflix.discovery: off
